{{ $root := . }}
{{ range .Values.storageGroupName }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "fastdfs-nginx.fullname" $root }}-storage-{{ . }}
  labels:
    app: {{ template "fastdfs-nginx.name" $root }}
    chart: {{ template "fastdfs-nginx.chart" $root }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
spec:
  type: {{ $.Values.service.type }}
  ports:
    - name: storage
      port: {{ $.Values.service.port.storage }}
      protocol: TCP
      targetPort: storage
    - name: storage-nginx
      port: {{ $.Values.service.port.storageNginx }}
      protocol: TCP
      targetPort: storage-nginx
  selector:
    app: {{ template "fastdfs-nginx.name" $root }}-storage-{{ . }}
    release: {{ $.Release.Name }}
---
{{- end }}
