{{- if and .Values.persistentVolume.enabled (not .Values.persistentVolume.existingClaim.tracker) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "fastdfs-nginx.fullname" . }}-tracker
  labels:
    app: {{ template "fastdfs-nginx.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  accessModes:
    - {{ .Values.persistentVolume.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistentVolume.size.tracker | quote }}
  {{- if .Values.persistentVolume.storageClass }}
    {{- if (eq "-" .Values.persistentVolume.storageClass) }}
  storageClassName: ""
    {{- else }}
  storageClassName: "{{ .Values.persistentVolume.storageClass }}"
    {{- end }}
  {{- end }}
{{- end }}
