apiVersion: v1
kind: Service
metadata:
  name: {{ template "fastdfs-nginx.fullname" . }}-tracker-headless
  labels:
    app: {{ template "fastdfs-nginx.name" . }}
    chart: {{ template "fastdfs-nginx.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- if .Values.headless.annotations }}
  annotations:
{{ .Values.headless.annotations | toYaml | trimSuffix "\n" | indent 4 }}
{{- end }}
spec:
  clusterIP: None
  ports:
{{- range $key, $port := .Values.trackerPorts }}
    - name: {{ $key }}
      port: {{ $port.containerPort }}
      targetPort: {{ $port.name }}
      protocol: {{ $port.protocol }}
{{- end }}
  selector:
    app: {{ template "fastdfs-nginx.name" . }}-tracker
    release: {{ .Release.Name }}
