apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  annotations:
    {{- if .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
    {{- if .Values.registry.service.annotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.registry.service.annotations "context" $ ) | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.registry.service.type }}
  {{- if and (eq .Values.registry.service.type "ClusterIP") .Values.registry.service.clusterIP }}
  clusterIP: {{ .Values.registry.service.clusterIP }}
  {{- end }}
  {{- if and .Values.registry.service.loadBalancerIP (eq .Values.registry.service.type "LoadBalancer") }}
  loadBalancerIP: {{ .Values.registry.service.loadBalancerIP }}
  externalTrafficPolicy: {{ .Values.registry.service.externalTrafficPolicy | quote }}
  {{- end }}
  {{- if and (eq .Values.registry.service.type "LoadBalancer") .Values.registry.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges: {{- toYaml .Values.registry.service.loadBalancerSourceRanges | nindent 4 }}
  {{- end }}
  ports:
    - name: TCP-{{ .Values.registry.service.targetPort }}
      port: {{ .Values.registry.service.port }}
      protocol: TCP
      targetPort: {{ .Values.registry.service.targetPort }}
      {{- if (and (or (eq .Values.registry.service.type "NodePort") (eq .Values.registry.service.type "LoadBalancer")) .Values.registry.service.nodePort) }}
      nodePort: {{ .Values.registry.service.nodePort }}
      {{- else if eq .Values.registry.service.type "ClusterIP" }}
      nodePort: null
      {{- end }}
  selector: {{ include "common.labels.matchLabels" . | nindent 4 }}
